package cards.monster;

public enum MonsterType {
	HEXER, DRACHE, ZOMBIE, KRIEGER, INSEKT, FELS, UNGEHEUER, FEE, PFLANZE, UNGEHEUER_KRIEGER, MASCHINE, AQUA, DINOSAURIER, UNTERWELTLER, FISCH, PYRO, REPTIL, DONNER, GEFLUEGELTES_UNGEHEUER, SEESCHLANGE; //usw.
}
