package cards.monster;

public enum MonsterType {
	/*
	 * Enumeration for the MonsterCard Types
	 */
	HEXER, DRACHE, ZOMBIE, KRIEGER, INSEKT, FELS, UNGEHEUER, FEE, PFLANZE, 
	UNGEHEUER_KRIEGER, MASCHINE, AQUA, DINOSAURIER, UNTERWELTLER, FISCH, PYRO, 
	REPTIL, DONNER, GEFLUEGELTES_UNGEHEUER, SEESCHLANGE;
}
